language: java
jdk:
- oraclejdk8
services: mongodb
install: mvn package -DskipTests=true
script: mvn verify
notifications:
  email:
    recipients:
    - maurizio@softinstigate.com
    on_success: always
